GRANT USAGE ON SCHEMA actualites TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA actualites TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA actualites TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA actualites TO "apps";