GRANT USAGE ON SCHEMA actualites TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA actualites TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA actualites TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA actualites TO "apps";
-- Grant permissions on new tables to user apps
ALTER DEFAULT PRIVILEGES IN SCHEMA actualites GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO "apps";
ALTER DEFAULT PRIVILEGES IN SCHEMA actualites GRANT EXECUTE ON FUNCTIONS TO "apps";
ALTER DEFAULT PRIVILEGES IN SCHEMA actualites GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "apps";